### ISSUE TITLE
typeHandler for interface gives a Class/TypeAlias not found error.

### ISSUE THREAD

**Issue by rsprinkle** [mybatis/mybatipse#71] opened 2017-01-17 02:12 UTC
The validator give a "Class/TypeAlias 'java.sql.Blob' not found." for the following declaration:

`<typeHandler javaType="java.sql.Blob"  jdbcType="BLOB"  handler="EMBlobHandler" />`

The declaration works fine in MyBatis.   I believe the problem is that the validator is expecting a concrete class.   I get an identical error for "java.sql.Clob".

**Comment by harawata** [comment] 2017-01-17 09:27
Hi,

I couldn't reproduce it.
MyBatipse does not check if it is an interface or a concrete class.
It seems that your Eclipse could not find these classes in the project's classpath, for some reason.
If cleaning the project didn't help, try creating a new workspace, please.

**Comment by kazuki43zoo** [comment] 2017-09-17 04:30
@rsprinkle Could you confirm @harawata 's comment?

**Comment by kenjdavidson** [comment] 2019-01-18 13:04
I also have this error, it happens on every typeAlias and typeHandler.  The classes are definitely found, as the Mybatis functionality works for both.  It's just the Mybatis XML validation that seems to not find the class.  

In my particular instance, the project is setup like this:
MainProject (pom = pom)
- Project_model (pom = jar)
- Project_common (pom = jar)
- Project_api (pom = war)

The Mybatis configuration is found in Project_common/src/resources while the types specified are found in Project_model.  I was planning on looking into this issue myself, if I have time and do it, I will update accordingly.

**Comment by harawata** [comment] 2019-01-19 12:55
@kenjdavidson ,
It's quite possible that the plugin does not support multi-module project.
It would be great if you could take a look.
Thank you!

**Comment by kenjdavidson** [comment] 2019-01-22 18:32
I couldn't replicate the original issue either.

With regards to my issue, it looks like the person on my team just had their build path configured incorrectly so the error was actually correct.  I should have noticed it the first time I looked by it was Friday.

Can probably close this.

**Comment by harawata** [comment] 2019-01-23 17:52
Thanks for the follow-up!
It's been a while with no reply from the reporter, so let's close.

**Closed by harawata** 2019-01-23 17:52 UTC
Labels: waiting for feedback
