### ISSUE TITLE
can't resolve two pice of mybatis file with a resultMap id in a namespace？

### ISSUE THREAD

**Issue by wttzxc** [mybatis/mybatipse#91] opened 2018-09-30 04:01 UTC

**Comment by harawata** [comment] 2018-09-30 12:12
I'm not sure what you mean. Please post an example.

**Comment by 913396391qq** [comment] 2018-11-09 05:47
class  userService{
     userDao.select(); // can not jump into xml of sql
}

interface userDao{
    select();  // but  here, can jump into xml of sql
}
use eclipse 4.5,can you reply it thanks

**Comment by harawata** [comment] 2018-11-09 16:43
@913396391qq ,
With that information, all I can say is 'it should work'. :)
And your problem looks different than the original report.
Please create a new issue with the details instead of adding a comment on an irrelevant issue.

I'll close this because there is not enough information to proceed.
Remember, to fix a problem, we need to reproduce it first.

**Closed by harawata** 2018-11-09 16:43 UTC
